on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install 11ty
        run: npm install @11ty/eleventy

      - name: Pre-build steps
        run: rm -rf site/*

      - name: Build site
        run: npx @11ty/eleventy

      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@v4
        with:
          nekoweb-api-key: ${{ secrets.API_KEY }}
          nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-folder: "site"
          directory: "site"
